### ISSUE TITLE
Consider integrating Geodesic distance

### ISSUE THREAD

**Issue by galewis2** [jedalong/wildlifeDI#1]
It would be useful to natively be able to convert from DD within this library

**Comment by jedalong** [comment]
Hi Thanks, I need to do a several things to update this package, but always failing to find the time. I am also awaiting the outcome of the sftraj project to see if i can then do a bunch of updates in concert with moving to a new sf trajectory format.

**Comment by LuisLauM** [comment]
> Hi Thanks, I need to do a several things to update this package, but always failing to find the time. I am also awaiting the outcome of the sftraj project to see if i can then do a bunch of updates in concert with moving to a new sf trajectory format.

Your package is very usefull for those ones that work with spatial data. Particularly, I am using to make some analysis of dyadic movement, so I would suggest to include some statistics reported in the 2018 Rocío Joo paper ([https://doi.org/10.1186/s40462-018-0144-2](https://doi.org/10.1186/s40462-018-0144-2)). Most of them are already included, but there are some other that will surely improve this library.

**Comment by jedalong** [comment]
Geodesic distances are now supported as of version 0.5.0 with the exception of the cr function.
