### ISSUE TITLE
rgeos archived

### ISSUE THREAD

**Issue by rsbivand** [jedalong/wildlifeDI#2]
@jedalong rgeos was archived three days ago, so please do move to submit an updated version of wildlifeDI as soon as possible. See https://github.com/r-spatial/evolution https://r-spatial.github.io/evolution/ for details.

**Comment by jedalong** [comment]
Hi Roger
I was hoping to wait and see what Clement Calenge was going to do with the adehabitatLT package, but will try to act on this ASAP to at least come up with a temporary solution. I will need to implement some more substantial longer term changes going forward if the adhabitatLT package is not updated. Thanks!

**Comment by rsbivand** [comment]
adehabitatLT doesn't use rgeos now, so if that was why it was suggested, I think it can be dropped.

**Comment by jedalong** [comment]
Package was updated with dependencies fixed.
