### ISSUE TITLE
No functions seem to recognize move2 class?

### ISSUE THREAD

**Issue by kaitlynvega** [jedalong/wildlifeDI#6]
I used mt_as_move2 from the move2 package to turn a data frame of trajectories from bighorn sheep into a move2 object, and I filtered the move2 object using the filtering function in move2. Despite this. every function I have tried from the wildlifeDI package has thrown an error saying:  "No pairs with temporal overlap found." Error Not all objects inherit the `move2` class.

I can look at the tracks for a pair of individuals and see that most of the points do in fact overlap (the collars are set to take GPS fixes at 4, 8, and 12 AM and PM every day). I even set my tc to 30 minutes (1800 seconds) to be abundantly sure it wasn't some weird rounding thing. What's the deal?

**Comment by jedalong** [comment]
What is the deal indeed Kaitlyn! can you post  or send me your code, as that seems like a move2 issue and the error and your assessment do not seem to align.

**Comment by kaitlynvega** [comment]
Hi Jed,

Thanks for your help. Here's some toy data and the code I used:


```
library(tidyverse)
library(wildlifeDI)
library(sf)
library(move2)
library(lubridate)

GPSDat <- data.frame(AnimalID = rep(c("HLS1", "HLS2"), each = 10),
                     Sex = rep(c("Male", "Female"), each = 10),
                     DateLocal = as_datetime(c(seq(1643281200, 1643410800, by = 14400), 
                                               seq(1643266800, 1643396400, by = 14400))),
                     Lat = runif(20, min = 45, max = 46),
                     Long = runif(20, min = -113, max = -112)) %>%
  st_drop_geometry()

track <- mt_as_move2(GPSDat, coords = c("Long", "Lat"),
                     time_column = "DateLocal",
                     track_id_column = "AnimalID")

sheep1 <- filter_track_data(track, .track_id = "HLS1")
sheep2 <- filter_track_data(track, .track_id = "HLS2")


Prox(sheep1, sheep2, tc = 30*60, dc = 50)
```

**Comment by jedalong** [comment]
There was an simple error in the code of the function checkTO such that when you input two tracks as you do here and they do not have any duplicate ids (which should be always) it did not correctly return the id pairs. I will fix this on GitHub and try to push to CRAN soon. In the meantime use devtools to install the updated version from github or download the checkTO function and load from your computer locally.

Thank you for identifying this error with a reproducible example.

**Comment by Kasi21** [comment]
Hi Jed, 

I'm encountering the same error that Kaitlyn observed when I use both my own data and the reproducible example with the Prox function. I've tried installing the most recent CRAN and GitHub versions and also downloading the CheckTO function to load from the computer locally, but I always get the error: 

"No pairs with temporal overlap found." Error Not all objects inherit the move2 class.

Do you have any ideas on what the issue might be & how to solve. 

Thanks in advance!
